-- Rollback-only checks; no real stories or users are changed.
begin;
insert into auth.users(id) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);
insert into public.travel_stories(id,owner_id,trip_id,story) values('cccccccc-cccc-4ccc-8ccc-cccccccccccc',auth.uid(),'test-trip','{}');
reset role;
set local role anon;
select set_config('request.jwt.claims','{"role":"anon"}',true);
do $$ begin if exists(select id from public.travel_stories where id='cccccccc-cccc-4ccc-8ccc-cccccccccccc') then raise exception 'FAIL: anonymous draft read';end if;end $$;
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);
update public.travel_stories set published=true where id='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
reset role;
set local role anon;
select set_config('request.jwt.claims','{"role":"anon"}',true);
do $$ begin if not exists(select id from public.travel_stories where id='cccccccc-cccc-4ccc-8ccc-cccccccccccc') then raise exception 'FAIL: anonymous published read';end if;end $$;
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb","role":"authenticated"}',true);
do $$ begin update public.travel_stories set published=false where id='cccccccc-cccc-4ccc-8ccc-cccccccccccc';if found then raise exception 'FAIL: foreign unpublish';end if;end $$;
insert into public.travel_story_reports(reporter_id,story_id,reason) values(auth.uid(),'cccccccc-cccc-4ccc-8ccc-cccccccccccc','Spam');
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);
do $$ begin if exists(select id from public.travel_story_reports) then raise exception 'FAIL: foreign report read';end if;end $$;
update public.travel_stories set published=false where id='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
reset role;
set local role anon;
select set_config('request.jwt.claims','{"role":"anon"}',true);
do $$ begin if exists(select id from public.travel_stories where id='cccccccc-cccc-4ccc-8ccc-cccccccccccc') then raise exception 'FAIL: unpublished story readable';end if;end $$;
rollback;
select 'PASS: public opt-in, draft privacy, foreign writes blocked, unpublishing, report privacy' as verification;
