'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {validPublicStory} from '@/lib/stories.mjs';
export default function AdminInbox(){
 const requestVersion=useRef(0);
 const [state,setState]=useState('open'),[page,setPage]=useState(0),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{const version=++requestVersion.current;try{const response=await fetch(`/api/admin/reports?state=${state}&page=${page}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);if(version===requestVersion.current){setError('');setData(body);}}catch(error){if(version===requestVersion.current)setError(error.message);}finally{if(version===requestVersion.current)setLoading(false);}},[state,page]);
 useEffect(()=>{const versionRef=requestVersion;const initial=setTimeout(load,0);const timer=setInterval(load,60000);return()=>{clearTimeout(initial);clearInterval(timer);versionRef.current++;};},[load]);
 const report=data?.reports.find(report=>report.id===selected);
 async function decide(event){event.preventDefault();const fields=new FormData(event.currentTarget);setSaving(true);setError('');try{const response=await fetch('/api/admin/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:report.id,action:fields.get('action'),note:fields.get('note'),reviewedAt:report.reviewed_at,hidden:report.moderation_hidden})});const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage('Decision saved and recorded in the audit trail.');setSelected('');await load();}catch(error){setError(error.message);}finally{setSaving(false);}}
 return <><div className="admin-toolbar"><div className="admin-open-count"><strong>{data?.openCount ?? '—'}</strong><span>reports awaiting review</span></div><div className="story-editor-actions"><label>Show<select value={state} onChange={event=>{setLoading(true);setState(event.target.value);setPage(0);setSelected('');}}><option value="open">Awaiting review</option><option value="reviewed">Reviewed</option><option value="all">All reports</option></select></label><button className="button secondary" disabled={loading || saving} onClick={()=>{setLoading(true);load();}}>Refresh inbox</button></div></div><p className="admin-refresh-note">Updates every minute while this page is open. Email and background alerts are not configured.</p>{error && <p role="alert" className="form-error">{error}</p>}{message && <p role="status" className="publish-success">{message}</p>}
 <div className="admin-inbox-grid"><section aria-label="Reports"><h2>{state==='open'?'Awaiting review':state==='reviewed'?'Reviewed reports':'All reports'}</h2>{loading && <p role="status">Refreshing reports…</p>}{data?.reports.map(item=><button className={'admin-report-card '+(selected===item.id?'selected':'')} key={item.id} onClick={()=>setSelected(item.id)}><span className="eyebrow">{item.reason} · {item.reviewed_at?'Reviewed':'Open'}</span><strong>{validPublicStory(item.story)?item.story.title:'Story content unavailable'}</strong><span>{new Date(item.created_at).toLocaleString()}</span><small>{item.moderation_hidden?'Hidden by moderation':item.published?'Public':'Unpublished'}</small></button>)}{data && !data.reports.length && !loading && <div className="panel empty"><h3>No reports in this view.</h3><p>New reader reports will appear here.</p></div>}<div className="story-editor-actions"><button className="button secondary" disabled={page===0||loading} onClick={()=>{setLoading(true);setPage(page-1);setSelected('');}}>Previous</button><span>Page {page+1}</span><button className="button secondary" disabled={!data || (page+1)*20>=data.total || loading} onClick={()=>{setLoading(true);setPage(page+1);setSelected('');}}>Next</button></div></section>
 <section className="panel admin-report-detail" aria-label="Review detail">{!report?<div className="empty"><h2>Select a report to review.</h2><p>Read the concern and story, then record your decision.</p></div>:<><div className="eyebrow">READER REPORT · {report.reason}</div><h2>{validPublicStory(report.story)?report.story.title:'Story content unavailable'}</h2><p className="admin-report-concern">{report.details || 'No additional details provided.'}</p>{validPublicStory(report.story) && <details open><summary>Story submitted for review</summary><div className="story-byline"><strong>By {report.story.author}</strong></div><p>{report.story.takeaway}</p>{report.story.memories.map((memory,index)=><article className="story-memory" key={index}><h3>{memory.name}</h3><p>{memory.description}</p></article>)}</details>}{report.published && !report.moderation_hidden && <Link href={'/stories/'+report.story_id} target="_blank" rel="noopener noreferrer">View public story ↗</Link>}
 <form className="travel-form" key={report.id} onSubmit={decide}><label>Decision<select name="action"><option value="resolve">Resolve report · leave story as it is</option><option value="hide">Hide story · block author from republishing</option><option value="restore">Lift moderation hold · author may publish again</option></select></label><label>Decision note<textarea name="note" maxLength={1000} required placeholder="Record what you checked and why you chose this action."/></label><p className="story-privacy">Hide removes public access immediately. Restore lifts the hold but leaves the story unpublished. Decision notes are visible only to administrators.</p><button className="button" disabled={saving}>{saving?'Saving decision…':'Apply decision'}</button></form><h3>Decision history</h3>{report.audit.length?report.audit.map((entry,index)=><article className="admin-audit-entry" key={index}><strong>{entry.action} · {new Date(entry.created_at).toLocaleString()}</strong><p>{entry.note}</p></article>):<p>No decisions yet.</p>}</>}</section></div></>;
}
