'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
export default function StoryPublisher({trip,notes,initiallyOpen=false}) {
 const router=useRouter();
 const [loading,setLoading]=useState(true),[open,setOpen]=useState(initiallyOpen),[preview,setPreview]=useState(null),[draft,setDraft]=useState(null),[published,setPublished]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let active=true;fetch('/api/stories?trip='+encodeURIComponent(trip.id)).then(r=>r.json()).then(body=>{if(active){setPublished(body.story || null);if(body.story?.story)setDraft({title:body.story.story.title,author:body.story.story.author,takeaway:body.story.story.takeaway,noteIds:[],savedMemories:body.story.story.memories});}}).catch(()=>{}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[trip.id]);
 async function save(input) {
  setBusy(true);setError('');try {const response=await fetch('/api/stories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,tripId:trip.id})});const body=await response.json();if(!response.ok)throw new Error(body.error);if(input.action==='publish'){router.push('/explore?published='+body.id);router.refresh();}else{setPublished(null);setPreview(null);setOpen(false);}}catch(error){setError(error.message);}finally{setBusy(false);}
 }
 return <section className={'panel story-publisher '+(open?'story-editor-open':'')}>
 {!open && <><div className="eyebrow">SHARE YOUR JOURNEY</div><h2>{published?.published?'Your story is live.':'A trip worth sharing.'}</h2><p>Choose a few memories and pass on what you learned.</p>{published?.published && <Link className="text-link" href={'/stories/'+published.id}>Read your story ↗</Link>}<div className="story-editor-actions"><button className="button" onClick={()=>setOpen(true)}>{published?.published?'Edit story':'Write a story'}</button>{published?.published && <button className="button secondary" disabled={busy} onClick={()=>save({action:'unpublish'})}>Unpublish</button>}</div></>}
 {open && <><ol className="story-progress" aria-label="Publishing steps"><li className={!preview?'current':''}>1 · Write</li><li className={preview?'current':''}>2 · Review</li><li>3 · Publish</li></ol>
 {loading ? <p role="status">Loading your story…</p> : !preview ? <form className="travel-form story-composer" onSubmit={event=>{event.preventDefault();const fields=new FormData(event.currentTarget);const next={title:fields.get('title'),author:fields.get('author'),takeaway:fields.get('takeaway'),noteIds:fields.getAll('noteIds')};if(next.noteIds.length>30){setError('Choose up to 30 memories.');return;}setError('');setDraft(next);setPreview(next);}}>
 <div className="story-editor-heading"><h2>Tell your story.</h2><p>{trip.city}, {trip.country}</p></div>
 <label>Story title<input name="title" defaultValue={draft?.title || trip.title} maxLength={150} required placeholder="A title for your journey"/></label>
 <label>Your name as the author<input name="author" defaultValue={draft?.author || ''} maxLength={60} required placeholder="Your name or pen name"/><small>This appears beside “By” on your story. Use a name, not the story title. Your email stays private.</small></label>
 <label>Your advice for another traveler<textarea name="takeaway" defaultValue={draft?.takeaway || ''} maxLength={1200} required placeholder="What was worth it? What would you do differently?" rows={4}/></label>
 <fieldset className="memory-selection"><legend>Memories to include</legend><p>Select up to 30. Only the selected memory text will be published.</p>{notes.length?notes.map(note=><label className="story-choice" key={note.id}><input type="checkbox" name="noteIds" value={note.id} defaultChecked={draft?.noteIds.includes(note.id) || draft?.savedMemories?.some(memory=>memory.name===note.name && memory.description===note.description)}/><span><strong>{note.name}</strong><small>{note.type} · {note.description.slice(0,100)}{note.description.length>100?'…':''}</small></span></label>):<p>No journal memories yet. You can still share your advice.</p>}</fieldset>
 <p className="story-privacy">Private photos, trip dates, budgets, and itinerary details are excluded.</p>
 <div className="story-editor-actions"><button className="button" type="submit">Preview story →</button><button className="button secondary" type="button" onClick={()=>setOpen(false)}>Cancel</button></div></form>
 : <div className="story-preview"><div className="eyebrow">THIS IS WHAT READERS WILL SEE</div><h2>{preview.title}</h2><div className="story-byline"><span className="story-author-avatar">{preview.author.trim().slice(0,1).toUpperCase()}</span><span><strong>By {preview.author}</strong><small>{trip.city}, {trip.country}</small></span></div><div className="story-takeaway"><h3>Advice for your journey</h3><p>{preview.takeaway}</p></div>{notes.filter(note=>preview.noteIds.includes(note.id)).map(note=><article className="story-memory" key={note.id}><div className="eyebrow">{note.type}</div><h3>{note.name}</h3><p>{note.description}</p></article>)}<p className="story-privacy">Publishing makes this story available to everyone. You can unpublish later, but external copies may remain.</p><div className="story-editor-actions"><button className="button" disabled={busy} onClick={()=>save({...preview,action:'publish',confirmPublic:true})}>{busy?'Publishing…':'Publish story →'}</button><button className="button secondary" disabled={busy} onClick={()=>setPreview(null)}>Back to writing</button></div></div>}
 </>}{error && <p role="alert" className="form-error">{error}</p>}</section>;
}
